Controllers films users
Advaito/java-filmorate pull request #2
Opened 2023-01-13 10:11 UTC by Advaito

2023-01-13 10:25 UTC, Advaito commented
Не понимаю тесты постмана и что там не так, проверял все сам и все работает корректно по тз

2023-01-14 12:31 UTC, ohelly requested changes
Привет! Отличная работа, видно, что проделана большая работа. Есть несколько замечаний, которые необходимо исправить. Также я оставил несколько рекомендаций, на которые стоит обратить внимание.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    List<Film> films = new ArrayList<>();
Необходимо исправить: Необходимо использовать модификаторы доступа.
Также есть вопрос по поводу хранения - Почему не используется Map? Ключом в ней может быть идентификатор записи, что будет правильнее и более похоже на хранилище из прошлых работ.

Также относится к UserController

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Component
Рекомендация: Аннотация ``@Component``в данном случае не нужна. Данной аннотацией(а также другими аннотациями спринга, например ``@Service``), мы обозначаем для спринга, что ему нужно загрузить данный класс в свой контекст, для того, чтобы он смог данный класс заинжектить при необходимости(инъекция происходит через конструктор или аннотацию ``@Autowired``). Но данный класс не несет в себе функциональную логику и мы его нигде не инжектим, это просто класс для отображения некой информации.

Рекомендация также относится к классу User

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @PatchMapping("/patch")
Необходимо исправить: Для обновления необходимо использовать метод PUT вместо PATCH. Метод PATCH используется для частичного обновления элемента. Например если создать метод, который обновляет только дату релиза у фильма, то он был бы PATCH.

Замечание справедливо и для UserController.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User updateUser(@RequestBody @Valid User user) {
Необходимо исправить: При обновлении пользователя также необходимо добавить проверку на то, что name == null, и если null подставлять на его место login.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final static Logger log = LoggerFactory.getLogger(UserController.class);
Рекомендация: Данную строку можно заменить ломбоковской аннотацией ``@Slf4j``, которая добавляет логгер и он нам будет доступен также через имя log

Рекомендация также относится к FilmController.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String description;
Необходимо исправить: По ТЗ не сказано, что описание не должно быть пустым, поэтому нет необходимости задавать нижнюю границу для данного поля.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LocalTime duration;
Рекомендация: Для данного поля можно задать тип Duration или любой числовой(Integer, Long). Тогда нам не придется писать свою аннотацию и использовать аннотацию ``@Positive``.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
Необходимо исправить: Поле id может быть null, например при создании, идентификатор должен задаваться внутри контроллера, поэтому необходимо убрать аннотацию ``@NotNull``.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String login;
Необходимо исправить: По ТЗ поле логин не должно содержать пробелы, но аннотация ``@NotBlank`` данный случай не проверяет. Поэтому необходимо добавить еще одну аннотацию: сделать свою кастомную для проверки на это или использовать аннотацию ``@Pattern`` и прописать для нее регулярное выражение.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/validations/CheckValidDate.java
> +        return localDate.isAfter(LocalDate.of(1985, 12, 28));
Необходимо исправить: Опечатка, год должен быть 1895. Также необходимо добавить проверку на null, если попробовать добавить фильм с releaseDate == null, то приложение упадет с ошибкой.

2023-01-14 12:31 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/validations/CheckValidDate.java
> +public class CheckValidDate implements ConstraintValidator<CustomValidDate, LocalDate> {
Здорово, что написаны собственные аннотации для проверок!

2023-01-14 12:31 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Необходимо исправить: Отсутствуют тесты. По ТЗ их необходимо добавить.

2023-01-16 11:22 UTC, Advaito commented
Использование мапы как мне кажется тут излишнее, проект накидан был за 30 минут чисто для понимания тестов по которым и задан был вопросик)  на счет аннотация компонент замечание не очень) если его убрать программа работать не будет) (очень тяжело работать без базы данных, лично мне намного проще было накидать крудешник через репу и поднять базу на докере чем вот эти костыли) все остальное сейчас поправлю и залью)

2023-01-23 23:18 UTC, Advaito commented
Я уже не знаю что делать что бы эти автотесты прошли... ендпоинты поправил как в тесте, в свагере все отрабатывает и вывод корректно

2023-01-24 20:52 UTC, ohelly requested changes
Привет! Супер, исправлены все замечания. Я оставил несколько рекомендаций, на которые стоит обратить внимание.

По поводу автотестов, считать как ошибки, которые необходимо исправить:
1) При попытке обновления не существующего пользователя в хранилище ничего не происходит, возвращается успешный ответ с входными данными. При попытке обновить несуществующего пользователя необходимо выкидывать эксепшен + добавить для этого тест
1.1) Точно такая же проблема и с обновлением несуществующего фильма. Исправить + добавить тест.
2) Поле duration для класса  Film необходимо сделать числовым, например Integer, так как в автотестах данное поле отправляется как число, например 100, а не как дата(1:10:11). Поэтому автотест падает, так ожидает успешное выполнение, но запрос не приходит из-за невозможности преобразовать 100 в LocalTime.

2023-01-25 21:37 UTC, ohelly approved these changes
Привет! Супер, исправлены все замечания. Работа принята, удачи в дальнейшем обучении!

Оставил одну рекомендацию, на которую стоит обратить внимание.

2023-01-25 21:37 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Рекомендация: Использование ResponseEntity в целом ок и допустимо, но обычно так не делают. Рассмотрим на примере метода обновления пользователя updateUser: Пусть возвращаемый тип будет User и он будет возвращаться при успешной операции, но если пользователя не существует необходимо просто выкинуть собственное исключение, например ``throw new UserNotFoundException("user with id " + user.getId() + " didn't find")``
Это исключение обычно должно наследоваться от RuntimeException:
``public class UserNotFoundException extends RuntimeException {//code here}``
Для чего делают именно так:
В зависимости от ТЗ случаев, когда может быть выкинут ексепшен много, например сущность не найдена(как в нашем случае) или ошибка валидации данных и многие другие. Далее для этого создается отдельный класс, обработчик ошибок(будете проходить позже), который уже в зависимости от исключения будет формировать то сообщение и тот статус, которые необходимо вернуть для конкретного исключения. При выкидывании исключения автоматически возвращается 500 статус ответа, если нет обработчика, который переопределяет данный статус

2023-01-26 15:10 UTC, merged