v2.00
Advaito/java-filmorate pull request #3
Opened 2023-02-05 19:18 UTC by Advaito

2023-02-05 19:22 UTC, Advaito commented
Про тесты знаю(допишу), подскажи что подправить)

2023-02-06 18:48 UTC, ohelly requested changes
Привет! Отметил несколько замечаний и рекомендаций, на которые стоит обратить внимание.

2023-02-06 18:48 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +package ru.yandex.practicum.filmorate.storage;
Рекомендация: Будет лучше если стораджки будут разделены по пакетам, то есть внутри пакета storage создать еще два дополнительных: user и film, в каждом из которых будет соответствующий интерфейс и его реализация.

2023-02-06 18:48 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new RuntimeException("Такого ID нет");
Рекомендация: Будет лучше, если создать отдельный ексепшен, например NotFoundException и выкидывать его, так как RuntimeException может произойти и в других случаях, что обработается в ExceptionController и вернется статус 404, что будет считаться не верно.

Рекомендация также относится и к InMemoryUserStorage

2023-02-06 18:48 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return films.get(id);
Необходимо исправить: Необходимо выкидывать ексепшен, если фильм не найден.

Замечание также относится и к InMemoryUserStorage

2023-02-06 18:48 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public void deleteFilm(Film film) {
Необходимо исправить: При удалении необходимо проверять, существует ли данный фильм и если его нет то выкидывать ексепшен.

Замечание также относится и к InMemoryUserStorage

2023-02-06 18:48 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .limit(count == null ? 10 : count)
Рекомендация: Дефолтное значение для количества популярных фильмов лучше вынести на уровень контроллера(у аннотации ``@RequestParam`` есть параметр "дефолтное значение"), пусть данный метод просто возвращает кол-во фильмов заданных во входном параметре.

2023-02-06 18:48 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionController.java
> +public class ExceptionController {
Рекомендация: возвращать в ответе ексепшен не самая лучшая идея. Во первых потому что пользователю будет ничего не понятно, а во вторых там будет показываться стек трейс ошибки, его не стоит выводить на всеобщее обозрение. Будет лучше вернуть строку, формата "error = " + e.getMessage();

2023-02-07 21:48 UTC, Advaito commented
Подскажи как пройти тесты постмана, потому что где он пишет что 500 еррор у меня либо 404 потому что такого пользователя или фильма нет или 200. я уже 2й раз не понимаю что с этими тестами не так вообще

2023-02-08 22:17 UTC, ohelly requested changes
Привет! Исправлены все прошлые замечания. Оставил комментарии по поводу тестов постмана, их нужно исправить. В случае вопросов можешь обратиться ко мне в пачку.

2023-02-08 22:17 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            films.put(film.getId(), film);
Необходимо исправить: Нашел проблему, почему не проходят тесты: Когда создается фильм или юзер у них инициализируется соответствующее поле, лайки или друзья. Но когда происходит обновление это поле никак не инициализируется(потому что в теле запроса это поле не указывается) и оно превращается в null, следовательно при дальнейших действиях с этими полям(добавить лайк/друга) вылетает NullPointerException.

2023-02-08 22:17 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (users.containsKey(user.getId())) {
Необходимо исправить: Нашел проблему, почему не проходят тесты: Когда создается фильм или юзер у них инициализируется соответствующее поле, лайки или друзья. Но когда происходит обновление это поле никак не инициализируется(потому что в теле запроса это поле не указывается) и оно превращается в null, следовательно при дальнейших действиях с этими полям(добавить лайк/друга) вылетает NullPointerException.

2023-02-12 14:42 UTC, ohelly approved these changes
Отлично! Теперь все работает корректно. Работа принята, удачи в дальнейшем обучении!

2023-02-13 17:34 UTC, merged