v3.00 full ref + add database
Advaito/java-filmorate pull request #4
Opened 2023-03-03 16:58 UTC by Advaito

2023-03-03 18:41 UTC, Advaito commented
Переписал почти весь код, проверил, переписал еще раз, проверил, еще поправил :D я уже не соображаю че с этими постман тестами не так, посмотри мож чего броситься в глаза)) (потому что там есть тест на вывод всех жанров так вот в нем 4 из 6 проходят хотя все создано верно и в свагере тоже выводит все верно)

2023-03-04 17:29 UTC, ohelly requested changes
Привет! Видно, что проделана огромная работа. Здорово, что используется пройденный материал. Я оставил ряд замечаний и рекомендаций. Замечания необходимо исправить.
К рекомендациям - прислушаться :)

Также есть замечание:
Не хватает картинки схемы в README.md

По поводу тестов: Есть замечания к моделям, возможно тесты падали из-за этого, давай сначала поправим то, что я отметил на этой проверке, а уже после посмотрим.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Genre> genres = genreService.getByFilmId(id);
Необходимо исправить: Необходимо вынести получение жанров из данного класса в класс FilmService, то есть сначала получаем фильм, а затем обогащаем его жанрами, сейчас объясню почему:
Сейчас при выборе одного фильма делается запрос на получение всех его жанров, но то же самое происходит при выборке всех фильмов, то есть на каждый фильм делается запрос на получение жанров, то есть на N фильмов приходится N запросов на получение жанров. Чтобы не нагружать нашу БД запросами, а также чтобы ускорить выполнение данной операции, получение жанров можно всегда делать за один запрос, независимо от кол-ва фильмов.
Здесь поможет запрос с оператором IN.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public User update(User user) {
Необходимо исправить: Отсутствует проверка на существование пользователя.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "UPDATE films " +
Необходимо исправить: Отсутствует проверка на существование фильма.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sqlQuery = "DELETE FROM users WHERE id = ?;";
Необходимо исправить: Отсутствует проверка на существование пользователя.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("Пользователь с id=" + id + " не существует");
Рекомендация: Нет необходимости проверять здесь на то, что user или friend == null, так как метод getById в UserStorage уже это подразумевает.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.update(user);
Необходимо исправить: При обновлении пользователя также необходимо проверять на то, что его name может быть null и проставлять в таком случае login.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.removeFriends(id, friendId);
Необходимо исправить: Добавить проверку на то, что пользователь и друг существуют. Можно здесь, либо в сторадже.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<User> getAllFriends(Long id) throws NotFoundException {
Рекомендация: Сейчас получение друзей идет в цикле, то есть выполняется N запросов на N друзей. От этого можно избавиться и сделать это с помощью одного запроса, воспользовавшись подзапросом и оператором IN.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            count = TOP;
Рекомендация: Для того чтобы не писать данное условие, можно использовать параметр defaultValue = "10" у аннотации ``@RequestParam`` в FilmController.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> -    private Set<Long> likes;
Необходимо исправить: Лайки тоже должны остаться.

2023-03-04 17:29 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        List<User> one = userService.getAllFriends(id);
Рекомендация: Данную операцию лучше вынести в сервисный слой, а еще лучше сделать это с помощью sql запросов.

2023-03-04 17:29 UTC, ohelly commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +public class FilmDbStorageTest {
Необходимо исправить: Очень мало тестов(относится ко всем классам). Необходимо написать тесты к сервисным слоям и написать тесты к основным операциям, таким как добавление в друзья, удаление из друзей, проставление лайков и тд.

2023-03-05 22:55 UTC, Advaito commented
Какая же боль работать с голой ждбс (в отличии от спринг даты и нормальной базы(хотя бы постгря)) :D 
Вроде все критичное подправил проверки сделал вроде все теперь лайки с друзьями вернул логику поправил) но увы тесты почему то валятся, и мне кажется что из-за генерации ключей (опять же беда голой ждбс :D) сейчас тесты дописываю новые

2023-03-06 02:41 UTC, Advaito commented
не продятся 2 теста( притом что абсолютно не могу понять, при выводе всех жанров ему не нравится 3 и 4ое название. а 2ой тож непонятен так как при обновлении все равно уникальные только остаются =_=

2023-03-06 19:13 UTC, ohelly requested changes
Привет! Осталось пара замечаний, также описал две проблемы по тестам. Жду исправлений!

2023-03-06 19:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.update(film);
Последняя проблема тут: После обновления мы возвращаем не обновленный фильм, а тот, который к нам пришел. Необходимо возвращать "свежий", из сервиса. В частности тест постмана падает на том, что они отправляют на обновлении фильм с дублирующими жанрами и ожидают в ответе, что вернутся только уникальные.
![image](https://user-images.githubusercontent.com/51891976/223207668-2fa6817e-ef94-4adb-855c-8fce1165ed63.png)

2023-03-06 19:15 UTC, ohelly commented
> Какая же боль работать с голой ждбс (в отличии от спринг даты и нормальной базы(хотя бы постгря)) :D Вроде все критичное подправил проверки сделал вроде все теперь лайки с друзьями вернул логику поправил) но увы тесты почему то валятся, и мне кажется что из-за генерации ключей (опять же беда голой ждбс :D) сейчас тесты дописываю новые

Согласен, со спрингом по-приятнее работать :)

2023-03-07 21:50 UTC, Advaito commented
С хибером было бы намного проще =_=

2023-03-08 14:50 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше :)

2023-03-10 13:21 UTC, merged